; Generated by scriptc (LLVM backend) from D:/proj/picots-master/test_scriptc.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrFfiTable = type { ptr, i64, i64, ptr, i8, ptr, ptr, i64, i64, i64, ptr, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_process_platform()
declare void @scr_str_release(ptr)
declare ptr @scr_crypto_random_uuid()
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare ptr @scr_str_concat(ptr, ptr)
declare void @scr_console_log(i64, ptr)

@sc_lit_0 = internal global { i64, i64, i64, [46 x i8] } { i64 -1, i64 45, i64 45, [46 x i8] c"PicoTS Native Backend Verification: platform=\00" }
@sc_lit_1 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c", uuid=\00" }

@sc_g_e_plat = internal global ptr null ; plat
@sc_g_e_uuid = internal global ptr null ; uuid
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %logargs = alloca [1 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = call ptr @scr_process_platform()
  %t2 = load ptr, ptr @sc_g_e_plat
  call void @scr_str_release(ptr %t2)
  store ptr %t1, ptr @sc_g_e_plat
  %t3 = call ptr @scr_crypto_random_uuid()
  %t4 = load ptr, ptr @sc_g_e_uuid
  call void @scr_str_release(ptr %t4)
  store ptr %t3, ptr @sc_g_e_uuid
  %t5 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t6 = load ptr, ptr @sc_g_e_plat
  %t7 = call ptr @scr_str_retain_v(ptr %t6)
  %t8 = call ptr @scr_str_concat(ptr %t5, ptr %t7)
  %t9 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t10 = call ptr @scr_str_concat(ptr %t8, ptr %t9)
  %t11 = load ptr, ptr @sc_g_e_uuid
  %t12 = call ptr @scr_str_retain_v(ptr %t11)
  %t13 = call ptr @scr_str_concat(ptr %t10, ptr %t12)
  %t14 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t14
  %t15 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t13, ptr %t15
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t5)
  call void @scr_str_release(ptr %t7)
  call void @scr_str_release(ptr %t8)
  call void @scr_str_release(ptr %t9)
  call void @scr_str_release(ptr %t10)
  call void @scr_str_release(ptr %t12)
  call void @scr_str_release(ptr %t13)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  ret void
}

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %g0 = load ptr, ptr @sc_g_e_plat
  call void @scr_str_release(ptr %g0) ; plat
  %g1 = load ptr, ptr @sc_g_e_uuid
  call void @scr_str_release(ptr %g1) ; uuid
  ret i32 0
}

attributes #0 = { sanitize_address }
