import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export function inlineAssetsToHeader(frontendDir: string): string {
  const htmlPath = join(frontendDir, "index.html");
  const cssPath = join(frontendDir, "styles.css");
  const jsPath = join(frontendDir, "app.js");

  let html = existsSync(htmlPath) ? readFileSync(htmlPath, "utf8") : "<html><body><h1>PicoTS App</h1></body></html>";
  const css = existsSync(cssPath) ? readFileSync(cssPath, "utf8") : "";
  const js = existsSync(jsPath) ? readFileSync(jsPath, "utf8") : "";

  // Inline CSS and JS into single standalone HTML bundle
  if (css) {
    if (html.includes('<link rel="stylesheet" href="styles.css">')) {
      html = html.replace('<link rel="stylesheet" href="styles.css">', `<style>\n${css}\n</style>`);
    } else if (html.includes("</head>")) {
      html = html.replace("</head>", `<style>\n${css}\n</style></head>`);
    } else {
      html += `<style>\n${css}\n</style>`;
    }
  }

  if (js) {
    if (html.includes('<script src="app.js"></script>')) {
      html = html.replace('<script src="app.js"></script>', `<script>\n${js}\n</script>`);
    } else if (html.includes("</body>")) {
      html = html.replace("</body>", `<script>\n${js}\n</script></body>`);
    } else {
      html += `<script>\n${js}\n</script>`;
    }
  }

  const htmlBuffer = Buffer.from(html, "utf8");
  const byteValues: string[] = [];
  for (let i = 0; i < htmlBuffer.length; i++) {
    byteValues.push(`0x${htmlBuffer[i].toString(16).padStart(2, "0")}`);
  }

  return `// AUTO-GENERATED BY PICOTS CLI - DO NOT EDIT
#pragma once
#include <stddef.h>

static const unsigned char g_embedded_html[] = {
  ${byteValues.join(", ")}, 0x00
};
static const size_t g_embedded_html_size = sizeof(g_embedded_html) - 1;
`;
}
