import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export function inlineAssetsToHeader(frontendDir: string): string {
  const htmlPath = join(frontendDir, "index.html");

  if (!existsSync(htmlPath)) {
    console.warn(`⚠️ [PicoTS] No index.html found in "${frontendDir}", using fallback template.`);
    const fallback = "<html><body style='background:#0b0f19;color:#fff;font-family:sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;'><h1>PicoTS App</h1></body></html>";
    return generateHeader(fallback);
  }

  let html = readFileSync(htmlPath, "utf8");

  // 1. Inline all <link rel="stylesheet" href="...">
  const cssRegex = /<link\s+[^>]*rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*>|<link\s+[^>]*href=["']([^"']+)["'][^>]*rel=["']stylesheet["'][^>]*>/gi;
  html = html.replace(cssRegex, (match, p1, p2) => {
    const href = p1 || p2;
    if (href.startsWith("http://") || href.startsWith("https://")) return match;
    const cleanPath = href.replace(/^\.?\//, "");
    const fullPath = join(frontendDir, cleanPath);
    if (existsSync(fullPath)) {
      const cssContent = readFileSync(fullPath, "utf8");
      return `<style>\n${cssContent}\n</style>`;
    }
    return match;
  });

  // 2. Inline all <script src="..."> (including type="module")
  const scriptRegex = /<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi;
  html = html.replace(scriptRegex, (match, src) => {
    if (src.startsWith("http://") || src.startsWith("https://")) return match;
    const cleanPath = src.replace(/^\.?\//, "");
    const fullPath = join(frontendDir, cleanPath);
    if (existsSync(fullPath)) {
      const jsContent = readFileSync(fullPath, "utf8");
      return `<script>\n${jsContent}\n</script>`;
    }
    return match;
  });

  return generateHeader(html);
}

function generateHeader(htmlContent: string): string {
  const htmlBuffer = Buffer.from(htmlContent, "utf8");
  const byteValues: string[] = [];
  for (let i = 0; i < htmlBuffer.length; i++) {
    byteValues.push(`0x${htmlBuffer[i].toString(16).padStart(2, "0")}`);
  }

  return `// AUTO-GENERATED BY PICOTS CLI - DO NOT EDIT
#pragma once
#include <stddef.h>

static const unsigned char g_embedded_html[] = {
  ${byteValues.join(", ")}, 0x00
};
static const size_t g_embedded_html_size = sizeof(g_embedded_html) - 1;
`;
}
